# Linear Algebra: Vector-Matrix-Scalar

## Ex1: Vectors

In [6]:
import numpy as np

 #### Câu 1:
        a) Viết hàm cal_vectors(op, u, v) với:
            op là một trong các toán tử +, -, *, /, "dot"
            u và v là 2 vectors (numpy array) 
        b) Thực hiện tính toán theo các toán tử với 2 vectors được truyền vào.

In [7]:
def cal_vectors(op,u,v):
  if op=='+':
    result = u + v
  elif op=='-':
    result = u-v
  elif op=='*':
    result = u*v
  elif op=='/':
    result = u/v
  elif op=='dot':
    result = u.dot(v)
  else: result = None
  return result

In [8]:
u=np.array([1, 3, 4, 6, 3, 4, 5])
v=np.array([4, 7, 1, 2, 3, 8, 9])
print('u=',u)
print('v=',v)

u= [1 3 4 6 3 4 5]
v= [4 7 1 2 3 8 9]


In [9]:
print('u+v=',cal_vectors('+',u,v))

u+v= [ 5 10  5  8  6 12 14]


In [10]:
print('u*v=',cal_vectors('*',u,v))

u*v= [ 4 21  4 12  9 32 45]


In [11]:
print('u.v=',cal_vectors('dot',u,v))

u.v= 127


#### Câu 2:
        Viết hàm cal_vector_norm(t, v) với:
            t là một trong các loại L1, L2, Max
            v là vector.


In [12]:
import numpy as np
from numpy.linalg import norm
import math

In [18]:
def cal_vector_norm(t,v):
    if t=='L1':
        result=norm(v,1)
    elif t=='L2':
        result=norm(v)
    elif t=='Max':
        result=norm(v,math.inf)
    else: result=None
    return result


In [14]:
v=np.array([1, 3, -4, 5, 7, 9, -6])
print('v=',v)

v= [ 1  3 -4  5  7  9 -6]


In [23]:
print('L1=',cal_vector_norm('L1',v))
print('L2=',cal_vector_norm('L2',v))
print('Max=',cal_vector_norm('Max',v))

L1= 35.0
L2= 14.730919862656235
Max= 9.0


## Ex2: Matrices

#### Câu 1:
        a) Viết hàm cal_matrices(op, m1, m2) với:
            op là một trong các toán tử +, -, *, /
            u và v là 2 ma trận (numpy array) 
        b) Thực hiện tính toán theo các toán tử với 2 ma trận được truyền vào.

In [24]:
import numpy as np

In [26]:
def cal_metrices(op,m1,m2):
    if op == '+':
        result=m1+m2
    elif op=='-':
        result=m1-m2
    elif op=='*':
        result=m1*m2
    elif op=='/':
        result=m1/m2
    else: result=None
    return result

In [27]:
m1 = np.array([[1, 3, 2, 4], [4, 3, 6, 8], [5, 6, 3, 1]])
print('M1     =\n', m1)

m2 = np.array([[2, 4, 5, 1], [5, 1, 2, 3], [1, 8, 1, 9]])
print('M2     =\n', m2)


M1     =
 [[1 3 2 4]
 [4 3 6 8]
 [5 6 3 1]]
M2     =
 [[2 4 5 1]
 [5 1 2 3]
 [1 8 1 9]]


In [30]:
print('M1+M2=\n',cal_metrices('+',m1,m2))
print('M1-M2=\n',cal_metrices('-',m1,m2))
print('M1*M2=\n',cal_metrices('*',m1,m2))
print('M1/M2=\n',cal_metrices('/',m1,m2))

M1+M2=
 [[ 3  7  7  5]
 [ 9  4  8 11]
 [ 6 14  4 10]]
M1-M2=
 [[-1 -1 -3  3]
 [-1  2  4  5]
 [ 4 -2  2 -8]]
M1*M2=
 [[ 2 12 10  4]
 [20  3 12 24]
 [ 5 48  3  9]]
M1/M2=
 [[0.5        0.75       0.4        4.        ]
 [0.8        3.         3.         2.66666667]
 [5.         0.75       3.         0.11111111]]


 #### Câu 2:
        Cho các ma trận A = [[1, 3, 3], [4, 5, 6], [7, 8, 9]] và 
                ma trận B = [[2, 3], [6, 8], [5, 7]]
        Thực hiện nhân 2 ma trận. 

In [31]:
import numpy as np

In [33]:
A=np.array([[1, 3, 3], [4, 5, 6], [7, 8, 9]])
print('A=\n',A)
B=np.array([[2, 3], [6, 8], [5, 7]])
print('B=\n',B)

A=
 [[1 3 3]
 [4 5 6]
 [7 8 9]]
B=
 [[2 3]
 [6 8]
 [5 7]]


In [35]:
print('A.B=\n',A.dot(B))
print('A.B=\n',A@B)

A.B=
 [[ 35  48]
 [ 68  94]
 [107 148]]
A.B=
 [[ 35  48]
 [ 68  94]
 [107 148]]


## Ex3: Vector, Matrix, Scalar

#### Câu 1:
        a) Viết hàm cal_scalar_mult(v, b) với:
            v là vector hoặc ma trận (numpy array)
            b là scalar.
        b) Hãy thực hiện tính toán theo vector/ma trận/scalar được truyền vào

In [ ]:
import numpy as np

In [36]:
def cal_scalar_mult(v,b):
    return v*b

In [37]:
#Ma trận
A=np.matrix([[4,5,2],[5,1,6]])
print('A=\n',A)
print('A*5=\n',cal_scalar_mult(A,5))


A=
 [[4 5 2]
 [5 1 6]]
A*5=
 [[20 25 10]
 [25  5 30]]


In [39]:
#Array
v=np.array([1,3,5,2,4])
print('v1=\n',v)
print('v1*5=\n',cal_scalar_mult(v,5))

v1=
 [1 3 5 2 4]
v1*5=
 [ 5 15 25 10 20]


#### Câu 2:
        a) Viết hàm cho phép người dùng nhập vào 1 ma trận A[mxn].
        b) Viết hàm cho phép người dùng nhập vào 1 vector v[n].
        c) Thực hiện phép nhân ma trận với vector trên.